# Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE file distributed with this work for additional information regarding copyright ownership. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.  

# This workflow will do a clean install of node dependencies, build the source code and run tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

name: CI

jobs:
  build:
    env:
      COMPOSEUI_SKIP_DOWNLOAD: 'true'
      DOTNET_CONSOLE_ANSI_COLOR: 'true'
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        node-version: [ '24.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ matrix.node-version }}
        COMPOSEUI_SKIP_DOWNLOAD: ${{env.COMPOSEUI_SKIP_DOWNLOAD}}

    - name: Install NPM dependencies
      run: npm ci

    - name: Build JavaScript
      run: npx lerna run build
    
    - name: Test JavaScript
      run: npx lerna run test

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install NuGet dependencies
      run: |
           powershell ./build/dotnet-restore.ps1


    - name: Build .NET
      run: |
           powershell ./build/dotnet-build.ps1


    - name: Test .NET
      run: |
           powershell ./build/dotnet-test.ps1


    - name: Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Pack .NET
      run: |
           powershell ./build/dotnet-pack.ps1

    - name: Upload Nuget Packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: packages
        path: ${{ github.workspace }}/packages

    - name: Upload Shell Binaries
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: shell-binaries
        path: ${{ github.workspace }}/src/shell/dotnet/src/Shell/bin/Release/net8.0-windows/
