name: Dependency Submission

on:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  dependency-submission:
    permissions: 
      id-token: write
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]
        node-version: [ '24.x' ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build Components
        run: |
              npm i
              npx lerna run build --stream
              powershell ./build/dotnet-restore.ps1
              powershell ./build/dotnet-build.ps1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@31f25a8de68ae5ce2ca274bc28546a78683c15ce # v0.1.4
        with:
          detectorsFilter: "NuGetProjectCentric,Npm,NpmLockfile3"
